name: demosaic-env
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - numpy>=2.0.2
  - pillow>=11.3.0
  - piexif>=1.1.3
  - pyyaml>=6.0.3
  - loguru>=0.7.3
  - scipy>=1.13.1
  - opencv