[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "numpy>=2.0.2",
    "scipy>=1.13.1",
    "pyyaml>=6.0.3",
    "pillow>=11.3.0",
    "piexif>=1.1.3",
    "loguru>=0.7.3",
    "opencv-python"
]
build-backend = "setuptools.build_meta"